baseurl = "/"

defaultContentLanguage = "es"
theme = "hello-friend-ng"

[Author]
  name = "Ariel D'Alessandro"


[permalinks]
  posts = "/posts/:year/:month/:title/"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Metadata mostly used in document's head
  description = "Peronal Technology blog"
  keywords = "homepage, blog, programming"
  images = [""]


  homeSubtitle = "Software Engineer"
  # Directory name of your blog content (default is `content/posts`)
  # contentTypeName = "posts"
  # Default theme "light" or "dark"
  defaultTheme = "dark"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/arielsempai"
  [[params.social]]
    name = "email"
    url = "mailto:dalessandro.ariel@gmail.com"
  [[params.social]]
    name = "github"
    url = "https://github.com/adalessa"

[languages]
  [languages.es]
    title = "Ariel D'Alessandro"
    subtitle = "Mi blog personal"
    keywords = "programacion php code"
    copyright = ""
    readOtherPosts = "Leer otros posts"

    [languages.es.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"
